# yaml-language-server: $schema=https://json.schemastore.org/pull-request-labeler-5.json
module:server:
  - changed-files:
      - all-globs-to-any-file: ["packages/server/**", "!**/scripts/**", "!**/docs/**"]
  - changed-files:
      - all-globs-to-any-file: ["packages/vcpkg/**", "!**/scripts/**", "!**/docs/**"]
  - changed-files:
      - all-globs-to-any-file: ["packages/tika/**", "!**/scripts/**", "!**/docs/**"]

module:nodes:
  - changed-files:
      - all-globs-to-any-file: ["nodes/**", "!**/scripts/**", "!**/docs/**"]

module:client-typescript:
  - changed-files:
      - all-globs-to-any-file: ["packages/client-typescript/**", "!**/scripts/**", "!**/docs/**"]

module:client-python:
  - changed-files:
      - all-globs-to-any-file: ["packages/client-python/**", "!**/scripts/**", "!**/docs/**"]

module:client-mcp:
  - changed-files:
      - all-globs-to-any-file: ["packages/client-mcp/**", "!**/scripts/**", "!**/docs/**"]

module:ai:
  - changed-files:
      - all-globs-to-any-file: ["packages/ai/**", "!**/scripts/**", "!**/docs/**"]

module:ui:
  - changed-files:
      - all-globs-to-any-file: ["apps/chat-ui/**", "!**/scripts/**", "!**/docs/**"]
  - changed-files:
      - all-globs-to-any-file: ["apps/dropper-ui/**", "!**/scripts/**", "!**/docs/**"]
  - changed-files:
      - all-globs-to-any-file: ["packages/shared-ui/**", "!**/scripts/**", "!**/docs/**"]

module:vscode:
  - changed-files:
      - all-globs-to-any-file: ["apps/vscode/**", "!**/scripts/**", "!**/docs/**"]

ci/cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file: "docker/**"

builder:
  - changed-files:
      - any-glob-to-any-file: "**/scripts/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
