/**
 * MIT License
 *
 * Copyright (c) 2026 Aparavi Software AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { execFile } from 'node:child_process';
import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import { promisify } from 'node:util';
import type { ServiceSummaryLite, StoreFs } from './types';

const run = promisify(execFile);
const PROJECT_DIR = '.projects';

const GIT_ENV = {
	GIT_AUTHOR_NAME: 'Rocket Agent',
	GIT_AUTHOR_EMAIL: 'agent@rocketride.ai',
	GIT_COMMITTER_NAME: 'Rocket Agent',
	GIT_COMMITTER_EMAIL: 'agent@rocketride.ai',
	// No global/user config: snapshot behavior must not vary by host.
	GIT_CONFIG_GLOBAL: '/dev/null',
	GIT_CONFIG_SYSTEM: '/dev/null',
};

// Only what the git binary itself needs to run (resolve its own path, find scratch
// space). Everything else in this (server) process's env — inference keys, vault
// URLs, encryption keys — is deliberately withheld from the child process.
const SAFE_ENV_PASSTHROUGH = ['PATH', 'HOME', 'SYSTEMROOT', 'TEMP', 'TMP'] as const;

function gitEnv(): NodeJS.ProcessEnv {
	const passthrough: NodeJS.ProcessEnv = {};
	for (const key of SAFE_ENV_PASSTHROUGH) {
		const value = process.env[key];
		if (value !== undefined) passthrough[key] = value;
	}
	return { ...passthrough, ...GIT_ENV };
}

async function git(workspaceDir: string, args: string[]): Promise<string> {
	const { stdout } = await run('git', args, { cwd: workspaceDir, env: gitEnv() });
	return stdout;
}

export interface SeedOpts {
	workspaceDir: string;
	pipePath: string;      // project-store-relative, e.g. 'demo/qa.pipe'
	store: StoreFs;
	docsDir: string;       // built assets/docs
	assetsDir: string;     // built assets root (AGENTS.md, agent/rr-builder.md)
}

export async function seedWorkspace(opts: SeedOpts): Promise<{ pipeFile: string }> {
	await fsp.mkdir(opts.workspaceDir, { recursive: true });
	// 1. The pipe, byte-identical from the store (string IO, no JSON round-trip).
	let pipeFile = '';
	if (opts.pipePath) {
		pipeFile = path.basename(opts.pipePath);
		const content = await opts.store.fsReadString(`${PROJECT_DIR}/${opts.pipePath}`);
		await fsp.writeFile(path.join(opts.workspaceDir, pipeFile), content, 'utf8');
	}
	// 2. AGENTS.md (generated by scripts/build-assets.mjs).
	await fsp.copyFile(path.join(opts.assetsDir, 'AGENTS.md'), path.join(opts.workspaceDir, 'AGENTS.md'));
	// 3. docs/.
	const docsOut = path.join(opts.workspaceDir, 'docs');
	await fsp.mkdir(docsOut, { recursive: true });
	for (const entry of await fsp.readdir(opts.docsDir)) {
		if (entry.endsWith('.md')) await fsp.copyFile(path.join(opts.docsDir, entry), path.join(docsOut, entry));
	}
	// 4. .opencode/agent/rr-builder.md.
	const agentOut = path.join(opts.workspaceDir, '.opencode', 'agent');
	await fsp.mkdir(agentOut, { recursive: true });
	await fsp.copyFile(path.join(opts.assetsDir, 'agent', 'rr-builder.md'), path.join(agentOut, 'rr-builder.md'));
	return { pipeFile };
}

export async function initGit(workspaceDir: string): Promise<void> {
	await git(workspaceDir, ['init', '--quiet', '--initial-branch=session']);
	await git(workspaceDir, ['add', '-A']);
	// --allow-empty: a session legitimately starts with no user files (the sidebar "New
	// session" creates one with no pipePath; the agent authors the pipe from scratch). Without
	// this, `git commit` exits 1 ("nothing to commit") and session creation 500s. The baseline
	// commit must always exist so commitTurn()/revert have a root to anchor to.
	await git(workspaceDir, ['commit', '--quiet', '--allow-empty', '-m', 'session start']);
}

/** One commit per agent file-change event (per-turn granularity, decided 2026-08-11). Null when clean. */
export async function commitTurn(workspaceDir: string, label: string): Promise<string | null> {
	await git(workspaceDir, ['add', '-A']);
	const status = await git(workspaceDir, ['status', '--porcelain']);
	if (!status.trim()) return null;
	await git(workspaceDir, ['commit', '--quiet', '-m', label]);
	return (await git(workspaceDir, ['rev-parse', 'HEAD'])).trim();
}

export async function listTurns(workspaceDir: string): Promise<Array<{ sha: string; label: string; at: string }>> {
	const out = await git(workspaceDir, ['log', '--format=%H%x09%s%x09%cI']);
	return out.trim().split('\n').filter(Boolean).map((line) => {
		const [sha, label, at] = line.split('\t');
		return { sha, label, at };
	});
}

/** Restore any prior turn's content as a NEW commit — history is never rewritten (audit trail). */
export async function revertTo(workspaceDir: string, sha: string): Promise<string> {
	await git(workspaceDir, ['checkout', sha, '--', '.']);
	// checkout doesn't delete files created after <sha>; clean them so the tree matches the turn.
	await git(workspaceDir, ['clean', '-fd']);
	const commit = await commitTurn(workspaceDir, `revert to ${sha.slice(0, 8)}`);
	return commit ?? sha;
}

export interface SaveBackOpts {
	workspaceDir: string;
	store: StoreFs;
	/** Store directory for a workspace pipe file; default sessions use the seeded pipe's directory. */
	storeDirFor: (pipeFile: string) => string;
}

/**
 * Write each workspace-root *.pipe back to the project store, PER FILE. A file that isn't valid
 * JSON is skipped (never written) and returned in `skipped` — one malformed/half-built pipe never
 * blocks the valid ones. This is the filesystem-sync contract behind auto-save-on-idle: every valid
 * change propagates to the store on its own; the caller surfaces `skipped` for visibility.
 */
export async function saveBack(opts: SaveBackOpts): Promise<{ written: string[]; skipped: string[] }> {
	const pipeFiles = (await fsp.readdir(opts.workspaceDir)).filter((f) => f.endsWith('.pipe'));
	const written: string[] = [];
	const skipped: string[] = [];
	for (const file of pipeFiles) {
		const text = await fsp.readFile(path.join(opts.workspaceDir, file), 'utf8');
		try {
			JSON.parse(text);
		} catch {
			skipped.push(file);
			continue;
		}
		const dir = opts.storeDirFor(file);
		await opts.store.fsWriteString(`${PROJECT_DIR}/${dir ? `${dir}/` : ''}${file}`, text);
		written.push(`${PROJECT_DIR}/${dir ? `${dir}/` : ''}${file}`);
	}
	return { written, skipped };
}

/**
 * Render the live component catalog as a compact, greppable markdown doc seeded at
 * `docs/COMPONENTS.md`. One line per real provider (`name (classType) — description · lanes`) so
 * the agent can `grep pdf` / `grep parse` to find a REAL provider instead of inventing one, then
 * `describe_component <name>` for config. The full `list_components` MCP output is ~60 KB and gets
 * truncated before the model sees it — this is the consumable substitute.
 */
export function formatComponentCatalog(services: Record<string, ServiceSummaryLite>): string {
	const lines = [
		'# RocketRide Components — this server\'s LIVE catalog',
		'',
		'Every provider that actually exists on this server is listed below. To pick a provider for a',
		'capability, grep this file (e.g. `grep -i pdf`, `grep -i parse`, `grep -i embed`). Use ONLY a',
		'`provider` name that appears here — if it is not in this list it does not exist, so never invent',
		'one (there is no `pdf_parser`). Then call `describe_component <name>` for its exact config schema.',
		'Do NOT dump `list_components` — it is ~60 KB and gets truncated.',
		'',
		'Format: `- **provider** (classType) — description · lanes: input→[outputs]`',
		'',
	];
	for (const name of Object.keys(services).sort()) {
		const s = services[name] ?? {};
		const cls = (s.classType ?? []).join('/') || 'component';
		// One concise sentence — full descriptions are ~400 chars each and bloat the file / grep hits.
		const full = (s.description ?? s.title ?? '').replace(/\s+/g, ' ').trim();
		const firstSentence = full.split(/(?<=\.)\s/)[0];
		const desc = (firstSentence.length <= 160 ? firstSentence : `${full.slice(0, 157).replace(/\s+\S*$/, '')}…`);
		const lanes = s.lanes
			? Object.entries(s.lanes)
					.map(([inLane, outs]) => `${inLane}→[${(outs ?? []).join(',')}]`)
					.join('  ')
			: '';
		lines.push(`- **${name}** (${cls})${desc ? ` — ${desc}` : ''}${lanes ? ` · lanes: ${lanes}` : ''}`);
	}
	return lines.join('\n') + '\n';
}

export async function workspaceSize(dir: string): Promise<number> {
	let total = 0;
	for (const entry of await fsp.readdir(dir, { withFileTypes: true })) {
		const p = path.join(dir, entry.name);
		if (entry.isDirectory()) total += await workspaceSize(p);
		else if (entry.isFile()) total += (await fsp.stat(p)).size;
	}
	return total;
}
