# =============================================================================
# MIT License
# Copyright (c) 2026 Aparavi Software AG
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# =============================================================================

"""
SQL safety validation shared across all relational database drivers.

The purpose of ``is_sql_safe`` is to filter out any unsafe SQL generated by an
LLM prior to being executed against a client's database.  The checks here are
dialect-agnostic standard SQL; individual drivers may add further restrictions
on top if needed.
"""

import re


def is_sql_safe(sql: str) -> bool:
    """Return False if the SQL contains potentially unsafe command statements.

    Allows safe usage of keywords in identifiers or strings.
    """
    # Strip comments first so embedded keywords in comments don't fool the
    # patterns, and so comment-based bypasses (e.g. /*!DROP*/) are neutralised.
    sql = re.sub(r'--.*?$', '', sql, flags=re.MULTILINE)  # Remove single-line comments
    sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)  # Remove block comments
    sql_lower = sql.lower()

    # Split on semicolons to check each individual statement separately.
    # A single input may contain multiple statements chained with ';'.
    statements = re.split(r';\s*', sql_lower.strip())

    # These patterns are anchored to the start of each statement (^) so that
    # keywords appearing as column names, aliases, or inside WHERE clauses are
    # not mistakenly flagged (e.g. "WHERE delete_flag = 1" is safe).
    forbidden_patterns = [
        r'^\s*(delete\s+from)',
        r'^\s*(insert\s+into)',
        r'^\s*update\s+\w+',
        r'^\s*drop\s+table',
        r'^\s*drop\s+database',
        r'^\s*alter\s+table',
        r'^\s*truncate\s+table',
        r'^\s*create\s+(table|database)',
        r'^\s*replace\s+into',
        r'^\s*merge\s+into',
        r'^\s*(exec|execute)\b',
        r'^\s*grant\b',
        r'^\s*revoke\b',
        r'^\s*use\s+\w+',
        r'^\s*call\s+\w+',
        r'^\s*load\s+data',
    ]

    for stmt in statements:
        for pattern in forbidden_patterns:
            if re.match(pattern, stmt):
                return False

        # SELECT ... INTO OUTFILE / INTO DUMPFILE can write arbitrary files on
        # the database server — block it even though it starts with SELECT.
        # This requires a non-anchored search across the whole statement because
        # the INTO clause appears after the column list, not at the start.
        if re.search(r'\bselect\b.*\binto\s+(outfile|dumpfile)\b', stmt, re.DOTALL):
            return False

    return True
