# =============================================================================
# MIT License
# Copyright (c) 2026 Aparavi Software AG
# =============================================================================

"""
SQL safety validation shared across all relational database drivers.

The purpose of ``is_sql_safe`` is to filter out any unsafe SQL generated by an
LLM prior to being executed against a client's database.  The checks here are
dialect-agnostic standard SQL; individual drivers may add further restrictions
on top if needed.
"""

import re


def is_sql_safe(sql: str) -> bool:
    """Return False if the SQL is not a read-only query.

    Uses a whitelist approach: only SELECT and WITH (CTE) statements are
    allowed.  Everything else is rejected.  This is safer than a blacklist
    because new or uncommon SQL commands (SET, COPY, PREPARE/EXECUTE, DO,
    HANDLER, etc.) are blocked by default.

    Fix F-04: added WITH to allowed_pattern so that CTE queries (which start
    with the WITH keyword) are correctly permitted instead of being silently
    rejected.
    """
    # Strip comments first so embedded keywords in comments don't fool the
    # patterns, and so comment-based bypasses (e.g. /*!DROP*/) are neutralised.
    sql = re.sub(r'--.*?$', '', sql, flags=re.MULTILINE)  # Remove single-line comments
    sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)  # Remove block comments

    # Split on semicolons to check each individual statement separately.
    statements = [s.strip() for s in re.split(r';\s*', sql.strip()) if s.strip()]

    # Only SELECT and WITH (common-table-expression leading into SELECT) are
    # allowed.  EXPLAIN is permitted as a prefix to either.
    # F-04 fix: WITH was missing from allowed_pattern despite being documented.
    allowed_pattern = re.compile(r'^\s*(explain\s+)?(select|with)\b', re.IGNORECASE)

    # Guard against CTEs that front DML (e.g. WITH cte AS (...) DELETE ...).
    # A statement starting with WITH must eventually resolve to a SELECT, not
    # INSERT / UPDATE / DELETE / MERGE.
    cte_dml_pattern = re.compile(
        r'\b(insert|update|delete|merge)\b', re.IGNORECASE
    )

    for stmt in statements:
        if not allowed_pattern.match(stmt):
            return False

        stmt_lower = stmt.lower()

        # SELECT ... INTO OUTFILE / INTO DUMPFILE can write arbitrary files on
        # the database server — block it even though it starts with SELECT.
        if re.search(r'\bselect\b.*\binto\s+(outfile|dumpfile)\b', stmt_lower, re.DOTALL):
            return False

        # WITH ... INSERT/UPDATE/DELETE/MERGE — CTE fronting a DML statement.
        if stmt_lower.lstrip().startswith('with') and cte_dml_pattern.search(stmt_lower):
            return False

    return True
