// MIT License
//
// Copyright (c) 2026 Aparavi Software AG
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// =============================================================================
// COMPONENT GALLERY — TOKEN USAGE (AUTO-GENERATED, DO NOT EDIT)
// =============================================================================

/**
 * Per-entry design-token usage, generated by
 * `scripts/generate-gallery-tokens.mjs` from the component sources and the
 * transitive commonStyles resolution over `themes/styles.ts`.
 *
 * Regenerate: `node scripts/generate-gallery-tokens.mjs` (from
 * packages/shared-ui). Verify without writing: pass `--check`.
 */

/** Token usage for one gallery entry. */
export interface IGalleryTokenUsage {
	/** Tokens referenced directly in the component sources. */
	direct: string[];
	/** commonStyles members the component uses -> tokens each contributes. */
	commonStyles: Record<string, string[]>;
}

/** Token usage keyed by gallery entry id (doc-only entries absent). */
export const GALLERY_TOKEN_USAGE: Record<string, IGalleryTokenUsage> = {
	'banner': {
		direct: ['--rr-color-error', '--rr-color-info', '--rr-color-warning'],
		commonStyles: {},
	},
	'button': {
		direct: ['--rr-bg-button', '--rr-border', '--rr-brand', '--rr-color-error', '--rr-fg-button', '--rr-text-primary'],
		commonStyles: {},
	},
	'card': {
		direct: ['--rr-bg-surface-alt', '--rr-bg-title', '--rr-border', '--rr-border-hover'],
		commonStyles: {
			card: ['--rr-bg-paper', '--rr-border'],
			cardHeader: ['--rr-bg-title', '--rr-text-primary'],
		},
	},
	'chat-view': {
		direct: ['--rr-bg-default', '--rr-bg-paper', '--rr-bg-scrollbar-thumb', '--rr-bg-widget', '--rr-border', '--rr-border-focus', '--rr-border-input', '--rr-brand', '--rr-color-error', '--rr-fg-button', '--rr-font-family', '--rr-font-family-widget', '--rr-font-mono', '--rr-font-size-widget', '--rr-text-caption', '--rr-text-disabled', '--rr-text-link', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			cardFlat: ['--rr-bg-paper', '--rr-border'],
			inputField: ['--rr-bg-input', '--rr-border-input', '--rr-text-primary'],
		},
	},
	'chip': {
		direct: ['--rr-border', '--rr-color-info', '--rr-text-primary'],
		commonStyles: {},
	},
	'confirm-dialog': {
		direct: ['--rr-font-family', '--rr-text-secondary'],
		commonStyles: {
			buttonDanger: ['--rr-brand', '--rr-color-error', '--rr-fg-button', '--rr-font-size-widget'],
			buttonPrimary: ['--rr-brand', '--rr-fg-button', '--rr-font-size-widget'],
			buttonSecondary: ['--rr-bg-paper', '--rr-border', '--rr-font-size-widget', '--rr-text-secondary'],
			modalDialog: ['--rr-bg-widget', '--rr-border', '--rr-shadow-widget'],
			modalFooter: ['--rr-border'],
			modalHeader: ['--rr-bg-title', '--rr-text-primary'],
		},
	},
	'connection-card': {
		direct: ['--rr-bg-paper', '--rr-border', '--rr-border-hover', '--rr-brand', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'content-header': {
		direct: ['--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'data-grid': {
		direct: ['--rr-bg-default', '--rr-bg-input', '--rr-bg-list-hover', '--rr-bg-paper', '--rr-bg-surface-alt', '--rr-border', '--rr-border-hover', '--rr-border-input', '--rr-brand', '--rr-chart-', '--rr-color-error', '--rr-color-info', '--rr-color-success', '--rr-color-warning', '--rr-fg-button', '--rr-font-family', '--rr-font-mono', '--rr-palette-mode', '--rr-shadow-widget', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			cardHeader: ['--rr-bg-title', '--rr-text-primary'],
			fontMono: ['--rr-font-mono'],
			inputField: ['--rr-bg-input', '--rr-border-input', '--rr-text-primary'],
			popupMenu: ['--rr-bg-paper', '--rr-border', '--rr-shadow-widget'],
			tableCell: ['--rr-border'],
		},
	},
	'detail-panel': {
		direct: ['--rr-bg-default', '--rr-border', '--rr-brand', '--rr-sash-hover', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			modalDialog: ['--rr-bg-widget', '--rr-border', '--rr-shadow-widget'],
		},
	},
	'drop-zone': {
		direct: ['--rr-border-hover', '--rr-brand', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'empty-state': {
		direct: ['--rr-bg-surface-alt', '--rr-border-hover', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'explorer': {
		direct: ['--rr-bg-input', '--rr-bg-list-active', '--rr-bg-list-hover', '--rr-bg-paper', '--rr-bg-surface-alt', '--rr-bg-toolbar-hover', '--rr-border', '--rr-brand', '--rr-color-error', '--rr-color-success', '--rr-color-warning', '--rr-fg-list-active', '--rr-font-family', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			labelUppercase: ['--rr-text-secondary'],
			textMuted: ['--rr-text-secondary'],
		},
	},
	'filter-strip': {
		direct: ['--rr-bg-default', '--rr-bg-input', '--rr-bg-list-hover', '--rr-bg-paper', '--rr-bg-surface-alt', '--rr-border', '--rr-border-hover', '--rr-border-input', '--rr-brand', '--rr-chart-', '--rr-color-error', '--rr-color-info', '--rr-color-success', '--rr-color-warning', '--rr-fg-button', '--rr-font-family', '--rr-font-mono', '--rr-palette-mode', '--rr-shadow-widget', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			cardHeader: ['--rr-bg-title', '--rr-text-primary'],
			fontMono: ['--rr-font-mono'],
			inputField: ['--rr-bg-input', '--rr-border-input', '--rr-text-primary'],
			popupMenu: ['--rr-bg-paper', '--rr-border', '--rr-shadow-widget'],
			tableCell: ['--rr-border'],
		},
	},
	'grid-helpers': {
		direct: ['--rr-bg-default', '--rr-bg-input', '--rr-bg-list-hover', '--rr-bg-paper', '--rr-bg-surface-alt', '--rr-border', '--rr-border-hover', '--rr-border-input', '--rr-brand', '--rr-chart-', '--rr-color-error', '--rr-color-info', '--rr-color-success', '--rr-color-warning', '--rr-fg-button', '--rr-font-family', '--rr-font-mono', '--rr-palette-mode', '--rr-shadow-widget', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			cardHeader: ['--rr-bg-title', '--rr-text-primary'],
			fontMono: ['--rr-font-mono'],
			inputField: ['--rr-bg-input', '--rr-border-input', '--rr-text-primary'],
			popupMenu: ['--rr-bg-paper', '--rr-border', '--rr-shadow-widget'],
			tableCell: ['--rr-border'],
		},
	},
	'input-field': {
		direct: ['--rr-bg-default', '--rr-text-disabled'],
		commonStyles: {
			inputField: ['--rr-bg-input', '--rr-border-input', '--rr-text-primary'],
		},
	},
	'mini-card': {
		direct: ['--rr-bg-paper', '--rr-border', '--rr-color-success', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'modal': {
		direct: ['--rr-font-family', '--rr-text-secondary'],
		commonStyles: {
			buttonDanger: ['--rr-brand', '--rr-color-error', '--rr-fg-button', '--rr-font-size-widget'],
			buttonPrimary: ['--rr-brand', '--rr-fg-button', '--rr-font-size-widget'],
			buttonSecondary: ['--rr-bg-paper', '--rr-border', '--rr-font-size-widget', '--rr-text-secondary'],
			modalDialog: ['--rr-bg-widget', '--rr-border', '--rr-shadow-widget'],
			modalFooter: ['--rr-border'],
			modalHeader: ['--rr-bg-title', '--rr-text-primary'],
		},
	},
	'section': {
		direct: ['--rr-border', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'sidebar-footer': {
		direct: ['--rr-bg-scrollbar-thumb', '--rr-bg-surface-alt', '--rr-brand', '--rr-color-success', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {
			divider: ['--rr-border'],
			popupMenu: ['--rr-bg-paper', '--rr-border', '--rr-shadow-widget'],
		},
	},
	'sidebar-menu': {
		direct: ['--rr-bg-list-active', '--rr-bg-list-hover', '--rr-fg-list-active', '--rr-text-disabled', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'status-badge': {
		direct: ['--rr-bg-surface-alt', '--rr-border', '--rr-color-error', '--rr-color-info', '--rr-color-success', '--rr-color-warning', '--rr-text-disabled', '--rr-text-secondary'],
		commonStyles: {},
	},
	'tab-control': {
		direct: ['--rr-bg-scrollbar-thumb', '--rr-bg-widget-header', '--rr-border', '--rr-brand', '--rr-color-error', '--rr-fg-button', '--rr-scrollbar-thumb', '--rr-text-primary', '--rr-text-secondary'],
		commonStyles: {},
	},
	'toggle-group': {
		direct: [],
		commonStyles: {
			toggleButton: ['--rr-border', '--rr-brand', '--rr-fg-button', '--rr-text-secondary'],
		},
	},
};
