# MIT License
#
# Copyright (c) 2026 Aparavi Software AG
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
/task/fetch — JWT-authenticated file download endpoint.

Serves files from the local filesystem store using short-lived JWT tokens
generated by ``FileStore.get_url()``. Cloud backends (S3, Azure) return
presigned URLs directly and bypass this endpoint entirely.

Features:
    - JWT validation with HS256 (signed with RR_SIGNING_KEY)
    - FileResponse for proper Content-Type and Range request support
    - No manual streaming — FastAPI/Starlette handles everything
"""

import os

import jwt
from fastapi import Request
from fastapi.responses import FileResponse, JSONResponse


def _decode_fetch_claim(token: str):
    """
    Decode and generation-gate a fetch capability token.

    Returns:
        ``(payload, None)`` on success or ``(None, error_response)`` on
        failure. Both fetch routes MUST validate through this helper so the
        decode options and the claim-generation gate can never diverge.

    The generation gate runs before anything else is read: `v` says how to
    interpret the rest of the payload. A v1 claim (pre-#1686) holds a WIRE
    path; served under today's meaning it would be a store-root-relative
    physical path into another user's tree — see FETCH_CLAIM_VERSION.
    """
    signing_key = os.environ.get('RR_SIGNING_KEY', '')
    if not signing_key:
        return None, JSONResponse({'error': 'Server signing key not configured'}, status_code=500)

    try:
        # Require the `exp` claim so a signed token without an expiration is
        # rejected rather than treated as non-expiring.
        payload = jwt.decode(token, signing_key, algorithms=['HS256'], options={'require': ['exp']})
    except jwt.ExpiredSignatureError:
        return None, JSONResponse({'error': 'Token expired'}, status_code=401)
    except jwt.InvalidTokenError as e:
        return None, JSONResponse({'error': f'Invalid token: {e}'}, status_code=401)

    from ai.account.file_store import FETCH_CLAIM_VERSION  # deferred: Account singleton

    if payload.get('v') != FETCH_CLAIM_VERSION:
        return None, JSONResponse({'error': 'Token format no longer supported'}, status_code=401)
    return payload, None


async def handle_fetch(request: Request):
    """
    Serve a file from the filesystem store, authenticated via JWT query param.

    The JWT payload must contain:
        - ``sub``: userId that the URL was issued to (audit trail only)
        - ``path``: RESOLVED physical store path (the capability — scope
          resolution and authorization ran at issuance, in FileStore.get_url)
        - ``v``: claim generation, which states what ``path`` MEANS. Only
          ``FETCH_CLAIM_VERSION`` is served; anything else is refused (see
          the version gate below)
        - ``exp``: expiration timestamp (standard JWT claim)
    """
    # ── Extract and validate JWT ─────────────────────────────────────────
    token = request.query_params.get('token')
    if not token:
        return JSONResponse({'error': 'Missing token parameter'}, status_code=401)

    payload, error = _decode_fetch_claim(token)
    if error is not None:
        return error

    user_id = payload.get('sub')
    path = payload.get('path')
    download_name = payload.get('download_name')
    if not user_id or not path:
        return JSONResponse({'error': 'Token missing required claims'}, status_code=400)

    # ── Map the signed store path to its filesystem location ─────────────
    # The `path` claim is the RESOLVED physical store path: authorization
    # happened at URL ISSUANCE (FileStore.get_url resolved+authorized under
    # the requesting session's identity), and the signed JWT is the
    # capability. Nothing is re-resolved here — scope re-resolution under an
    # internal identity would deny name-based '@/Team/<name>' and '@/Org'
    # spellings (no name dictionary, no org context) and 500 the fetch.
    from ai.account import Store

    backend = Store.instance()._store
    # _get_full_path guards traversal (raises on escape); a malformed claim
    # is indistinguishable from a missing file to the caller.
    try:
        abs_path = backend._get_full_path(path)
    except Exception:
        return JSONResponse({'error': 'File not found'}, status_code=404)

    if not abs_path.is_file():
        return JSONResponse({'error': 'File not found'}, status_code=404)

    # ── Serve the file ───────────────────────────────────────────────────
    # FileResponse handles Content-Type (from extension), Content-Length,
    # Range requests (HTTP 206), and streaming automatically.
    #
    # If the token carries a download_name, force a download with that filename
    # (Content-Disposition: attachment). Otherwise serve inline so media
    # viewers can stream the file (video/audio/pdf) in the browser.
    if download_name:
        return FileResponse(
            path=str(abs_path),
            filename=download_name,
            headers={
                'Cache-Control': 'private, max-age=3600',
                'Accept-Ranges': 'bytes',
            },
        )
    return FileResponse(
        path=str(abs_path),
        content_disposition_type='inline',
        headers={
            'Cache-Control': 'private, max-age=3600',
            'Accept-Ranges': 'bytes',
        },
    )


async def handle_fetch_dir(request: Request):
    """
    Serve one file from a signed DIRECTORY capability (app bundles).

    Route shape: ``/task/fetch/{token}/{subpath:path}``. Module Federation
    remotes are multi-file — ``remoteEntry.js`` fetches async chunks RELATIVE
    to its own URL — so the token rides the PATH (not a query param): every
    relative chunk request the browser derives from the entry URL then
    carries the same token automatically.

    The JWT payload must contain:
        - ``sub``: issuing subject (audit trail only)
        - ``dir``: RESOLVED physical store path of the authorized DIRECTORY
          (the capability — authorization ran at issuance, see
          ``file_store.mint_directory_url``)
        - ``v``:  claim generation gate (``FETCH_CLAIM_VERSION``)
        - ``exp``: expiration timestamp
    """
    token = request.path_params.get('token', '')
    subpath = request.path_params.get('subpath', '')
    if not token or not subpath:
        return JSONResponse({'error': 'Missing token or path'}, status_code=401)

    payload, error = _decode_fetch_claim(token)
    if error is not None:
        return error

    dir_claim = payload.get('dir')
    if not payload.get('sub') or not dir_claim or not isinstance(dir_claim, str):
        return JSONResponse({'error': 'Token missing required claims'}, status_code=400)

    # The subpath must stay INSIDE the signed directory: reject absolute
    # forms and any '..' segment before joining. (_get_full_path guards the
    # store root; this guards the capability's own boundary.)
    segments = [s for s in subpath.replace('\\', '/').split('/') if s not in ('', '.')]
    if not segments or any(s == '..' for s in segments):
        return JSONResponse({'error': 'File not found'}, status_code=404)

    from ai.account import Store

    backend = Store.instance()._store
    try:
        abs_path = backend._get_full_path(f'{dir_claim.rstrip("/")}/{"/".join(segments)}')
    except Exception:
        return JSONResponse({'error': 'File not found'}, status_code=404)

    if not abs_path.is_file():
        return JSONResponse({'error': 'File not found'}, status_code=404)

    # Bundle directories are immutable (one upload, one hash) — cache hard.
    # Content-Type comes from the file extension (remoteEntry.js → JS).
    return FileResponse(
        path=str(abs_path),
        content_disposition_type='inline',
        headers={
            'Cache-Control': 'private, max-age=86400, immutable',
            'Accept-Ranges': 'bytes',
        },
    )
