// MIT License
//
// Copyright (c) 2026 Aparavi Software AG
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// =============================================================================
// GENERATED by `./builder client-typescript:freeze` — do not edit by hand.
// =============================================================================

import type * as ClientApiV1_3 from './versions/v1.3';

/** Registry mapping each frozen SDK floor key (MAJOR.MINOR) to its value-surface snapshot. */
export interface ClientApiVersions {
	'1.3': typeof ClientApiV1_3;
}

/**
 * The newest frozen SDK floor — a convenience alias for consumers.
 *
 * Accumulation is NOT an intersection of versions: the "nothing ever frozen
 * can be removed" guarantee is the per-version floors in the package's
 * src/contract-check.generated.ts, which assert the live surface still
 * satisfies EACH frozen floor separately.
 */
export type ClientApiLatest = ClientApiVersions['1.3'];

export type * from './latest';
