/**
 * MIT License
 *
 * Copyright (c) 2026 Aparavi Software AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { createCipheriv, createHmac, randomBytes } from 'node:crypto';
import { EnvKeyResolver } from '../src/index';
import { fernetDecrypt, SaasVaultKeyResolver } from '../src/keys';
import * as http from 'node:http';

/** Spec-faithful Fernet encrypt for tests (v0x80, ts, iv, AES-128-CBC, HMAC-SHA256). */
function fernetEncrypt(plaintext: Buffer, key: string): string {
	const keyBytes = Buffer.from(key, 'base64url');
	const signingKey = keyBytes.subarray(0, 16);
	const encKey = keyBytes.subarray(16);
	const iv = randomBytes(16);
	const ts = Buffer.alloc(8);
	ts.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 1000)));
	const cipher = createCipheriv('aes-128-cbc', encKey, iv);
	const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
	const signed = Buffer.concat([Buffer.from([0x80]), ts, iv, ct]);
	const hmac = createHmac('sha256', signingKey).update(signed).digest();
	return Buffer.concat([signed, hmac]).toString('base64url');
}

const KEY = randomBytes(32).toString('base64url');

describe('fernetDecrypt', () => {
	test('round-trips', () => {
		const token = fernetEncrypt(Buffer.from('{"AGENT_ANTHROPIC_KEY":"sk-a"}'), KEY);
		expect(fernetDecrypt(token, KEY).toString()).toBe('{"AGENT_ANTHROPIC_KEY":"sk-a"}');
	});
	test('rejects a tampered token', () => {
		const token = fernetEncrypt(Buffer.from('x'), KEY);
		const bad = Buffer.from(token, 'base64url');
		bad[12] ^= 0xff;
		expect(() => fernetDecrypt(bad.toString('base64url'), KEY)).toThrow(/HMAC/);
	});

	// VERIFY V4: decrypts a real vector generated by Python `cryptography.fernet.Fernet`
	// (key/token captured from `Fernet.generate_key()` + `Fernet(key).encrypt(...)` —
	// confirms wire-format compatibility with extension/src/extension/saas/crypto.py).
	test('decrypts a vector generated by Python cryptography.fernet', () => {
		const pyKey = 'WTSS4KuZdh1FClZ2ofgT9kHUZ7oCO1uGTRiQpJpKx54='; // gitleaks:allow — Fernet test key, not a credential
		const pyToken = // gitleaks:allow — Fernet test token, not a credential
			'gAAAAABqe8ri2ZWhh4vyyYSZHoB5oQWwuCF0VWtad7dYkyh7u7bSSF8_w7Lp8ill5TyzBmPQJWGZnprz4fg2sh2bItvazWwvtlL3CfRw51Wneyyq3yahKYw0URW2IqllHeQJXtNM8meL';
		expect(fernetDecrypt(pyToken, pyKey).toString('utf8')).toBe('{"AGENT_ANTHROPIC_KEY":"sk-python-vector"}');
	});
});

describe('resolvers', () => {
	test('EnvKeyResolver reads AGENT_* from env', async () => {
		const keys = await new EnvKeyResolver({ AGENT_OPENAI_KEY: 'sk-o' } as NodeJS.ProcessEnv).resolve();
		expect(keys).toEqual({ anthropic: undefined, openai: 'sk-o' });
	});

	test('SaasVaultKeyResolver fetches blob with the user token and decrypts locally', async () => {
		const blob = fernetEncrypt(Buffer.from('{"AGENT_ANTHROPIC_KEY":"sk-vault"}'), KEY);
		let seenAuth = '';
		const srv = http.createServer((req, res) => {
			seenAuth = req.headers.authorization ?? '';
			res.setHeader('content-type', 'application/json');
			res.end(JSON.stringify({ encrypted: blob }));
		});
		await new Promise<void>((r) => srv.listen(0, '127.0.0.1', r));
		const port = (srv.address() as { port: number }).port;
		try {
			const resolver = new SaasVaultKeyResolver(`http://127.0.0.1:${port}`, KEY);
			const keys = await resolver.resolve('zitadel-token-1');
			expect(seenAuth).toBe('Bearer zitadel-token-1');
			expect(keys.anthropic).toBe('sk-vault');
		} finally {
			srv.close();
		}
	});
});
