/**
 * MIT License
 *
 * Copyright (c) 2026 Aparavi Software AG
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { createCipheriv, createHmac, randomBytes } from 'node:crypto';
import { EnvKeyResolver } from '../src/index';
import { FallbackKeyResolver, fernetDecrypt, SaasVaultKeyResolver, UserVarKeyResolver } from '../src/keys';
import type { InferenceSettings, KeyResolver } from '../src/types';
import * as http from 'node:http';

/** Spec-faithful Fernet encrypt for tests (v0x80, ts, iv, AES-128-CBC, HMAC-SHA256). */
function fernetEncrypt(plaintext: Buffer, key: string): string {
	const keyBytes = Buffer.from(key, 'base64url');
	const signingKey = keyBytes.subarray(0, 16);
	const encKey = keyBytes.subarray(16);
	const iv = randomBytes(16);
	const ts = Buffer.alloc(8);
	ts.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 1000)));
	const cipher = createCipheriv('aes-128-cbc', encKey, iv);
	const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
	const signed = Buffer.concat([Buffer.from([0x80]), ts, iv, ct]);
	const hmac = createHmac('sha256', signingKey).update(signed).digest();
	return Buffer.concat([signed, hmac]).toString('base64url');
}

const KEY = randomBytes(32).toString('base64url');

describe('fernetDecrypt', () => {
	test('round-trips', () => {
		const token = fernetEncrypt(Buffer.from('{"AGENT_ANTHROPIC_KEY":"sk-a"}'), KEY);
		expect(fernetDecrypt(token, KEY).toString()).toBe('{"AGENT_ANTHROPIC_KEY":"sk-a"}');
	});
	test('rejects a tampered token', () => {
		const token = fernetEncrypt(Buffer.from('x'), KEY);
		const bad = Buffer.from(token, 'base64url');
		bad[12] ^= 0xff;
		expect(() => fernetDecrypt(bad.toString('base64url'), KEY)).toThrow(/HMAC/);
	});

	// VERIFY V4: decrypts a real vector generated by Python `cryptography.fernet.Fernet`
	// (key/token captured from `Fernet.generate_key()` + `Fernet(key).encrypt(...)` —
	// confirms wire-format compatibility with extension/src/extension/saas/crypto.py).
	test('decrypts a vector generated by Python cryptography.fernet', () => {
		const pyKey = 'WTSS4KuZdh1FClZ2ofgT9kHUZ7oCO1uGTRiQpJpKx54='; // gitleaks:allow — Fernet test key, not a credential
		const pyToken = // gitleaks:allow — Fernet test token, not a credential
			'gAAAAABqe8ri2ZWhh4vyyYSZHoB5oQWwuCF0VWtad7dYkyh7u7bSSF8_w7Lp8ill5TyzBmPQJWGZnprz4fg2sh2bItvazWwvtlL3CfRw51Wneyyq3yahKYw0URW2IqllHeQJXtNM8meL';
		expect(fernetDecrypt(pyToken, pyKey).toString('utf8')).toBe('{"AGENT_ANTHROPIC_KEY":"sk-python-vector"}');
	});
});

describe('resolvers', () => {
	test('EnvKeyResolver reads AGENT_* from env', async () => {
		const settings = await new EnvKeyResolver({ AGENT_OPENAI_KEY: 'sk-o' } as NodeJS.ProcessEnv).resolve();
		expect(settings).toEqual({ keys: { openai: 'sk-o' }, model: undefined });
	});

	test('SaasVaultKeyResolver fetches blob with the user token and decrypts locally', async () => {
		const blob = fernetEncrypt(Buffer.from('{"AGENT_ANTHROPIC_KEY":"sk-vault"}'), KEY);
		let seenAuth = '';
		const srv = http.createServer((req, res) => {
			seenAuth = req.headers.authorization ?? '';
			res.setHeader('content-type', 'application/json');
			res.end(JSON.stringify({ encrypted: blob }));
		});
		await new Promise<void>((r) => srv.listen(0, '127.0.0.1', r));
		const port = (srv.address() as { port: number }).port;
		try {
			const resolver = new SaasVaultKeyResolver(`http://127.0.0.1:${port}`, KEY);
			const settings = await resolver.resolve('zitadel-token-1');
			expect(seenAuth).toBe('Bearer zitadel-token-1');
			expect(settings.keys.anthropic).toBe('sk-vault');
		} finally {
			srv.close();
		}
	});

	describe('UserVarKeyResolver', () => {
		const fakeEnv = { ROCKETRIDE_OPENAI_KEY: 'sk-o', ROCKETRIDE_DEEPSEEK_KEY: 'sk-d', ROCKETRIDE_AGENT_MODEL: 'openai/gpt-5.6-luna', UNRELATED: 'x' };
		const storeFactory = async () => ({ account: { getEnv: async () => fakeEnv } } as any);

		test('maps ROCKETRIDE_*_KEY -> provider id and reads the model', async () => {
			const r = await new UserVarKeyResolver(storeFactory).resolve('cred');
			expect(r.keys).toEqual({ openai: 'sk-o', deepseek: 'sk-d' });
			expect(r.model).toBe('openai/gpt-5.6-luna');
		});

		test('falls back to empty (no throw) when the store lacks account/get_env', async () => {
			const r = await new UserVarKeyResolver(async () => ({} as any)).resolve('cred');
			expect(r).toEqual({ keys: {} });
		});
	});

	// Finding 1 regression: SaaS mode wires keys = FallbackKeyResolver(UserVarKeyResolver, SaasVaultKeyResolver)
	// (src/index.ts) so the gear-settings user-variables (all providers incl. deepseek, plus the
	// model) resolve FIRST, with the vault blob only filling a provider the user hasn't set in
	// user-variables. Exercise that exact composition here with a stub standing in for the vault
	// HTTP call (already covered by the 'SaasVaultKeyResolver fetches blob...' test above).
	describe('FallbackKeyResolver (SaaS composition: user-variables primary, vault fallback)', () => {
		const fakeEnv = { ROCKETRIDE_DEEPSEEK_KEY: 'sk-d', ROCKETRIDE_AGENT_MODEL: 'deepseek/deepseek-chat' };
		const storeFactory = async () => ({ account: { getEnv: async () => fakeEnv } } as any);
		const vaultStub: KeyResolver = { resolve: async (): Promise<InferenceSettings> => ({ keys: { openai: 'sk-vault' } }) };

		test('resolves deepseek key + model from user-variables, and fills the gap from the vault fallback', async () => {
			const saasKeys = new FallbackKeyResolver(new UserVarKeyResolver(storeFactory), vaultStub);
			const settings = await saasKeys.resolve('cred');
			expect(settings.keys.deepseek).toBe('sk-d');
			expect(settings.model).toBe('deepseek/deepseek-chat');
			// openai was never set in user-variables -> the vault fallback fills that gap.
			expect(settings.keys.openai).toBe('sk-vault');
		});

		test('user-variables win over the vault fallback for a provider set in both', async () => {
			const overlapEnv = { ROCKETRIDE_OPENAI_KEY: 'sk-uservar' };
			const saasKeys = new FallbackKeyResolver(
				new UserVarKeyResolver(async () => ({ account: { getEnv: async () => overlapEnv } } as any)),
				vaultStub,
			);
			const settings = await saasKeys.resolve('cred');
			expect(settings.keys.openai).toBe('sk-uservar');
		});
	});
});
