# =============================================================================
# MIT License
# Copyright (c) 2024 RocketRide Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# =============================================================================

import re


# The purpose of is_sql_safe is to filter out any unsafe SQL generated by the invoked LLM
# prior to being executed on a client's DB


def is_sql_safe(sql: str) -> bool:
    """Return False if the SQL contains potentially unsafe command statements.

    Allows safe usage of keywords in identifiers or strings.
    """
    # Normalize: remove comments
    sql = re.sub(r'--.*?$', '', sql, flags=re.MULTILINE)  # Remove single-line comments
    sql = re.sub(r'/\*.*?\*/', '', sql, flags=re.DOTALL)  # Remove block comments
    sql_lower = sql.lower()

    # Extract individual SQL statements (split on semicolon or by start of query)
    statements = re.split(r';\s*', sql_lower.strip())

    # Forbidden patterns only at the start of statements or logical clauses
    forbidden_patterns = [
        r'^\s*(delete\s+from)',
        r'^\s*(insert\s+into)',
        r'^\s*update\s+\w+',
        r'^\s*drop\s+table',
        r'^\s*drop\s+database',
        r'^\s*alter\s+table',
        r'^\s*truncate\s+table',
        r'^\s*create\s+(table|database)',
        r'^\s*replace\s+into',
        r'^\s*merge\s+into',
        r'^\s*(exec|execute)\b',
        r'^\s*grant\b',
        r'^\s*revoke\b',
        r'^\s*use\s+\w+',
        r'^\s*call\s+\w+',
        r'^\s*load\s+data',
    ]

    for stmt in statements:
        for pattern in forbidden_patterns:
            if re.match(pattern, stmt):
                return False

    return True
