name: DCO Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  dco:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - uses: tisonkun/actions-dco@v1.2
