name: Lint PR

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.event.pull_request.head.ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
